Clinic_site-Django/clinic/clinic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('visits.urls')),
    path('admin/', admin.site.urls),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

Clinic_site-Django/clinic/visits/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('appointment/new/', views.select_department, name='appointment'),
    path('appointment/history/', views.PatientVisitsListView.as_view(), name='appointment-active'),
    path('patientcard/<int:pk>/', views.patient_card, name='patient-card'),
    path('appointment/new/<department>/', views.new_appointment, name='new-appointment'),
    path('patient_register/', views.PatientRegister.as_view(), name='patient_register'),
    path('doctor_register/', views.DoctorRegister.as_view(), name='doctor_register'),
    path('doctors/', views.DoctorListView.as_view(), name='doctors_list'),
    path('appointment/<int:pk>', views.patient_card_detail, name='visit-detail'),
    path('appointment/<int:pk>/update', views.patient_card_edit, name='visit-update'),
    path('patients/', views.PatientListView.as_view(), name='patients_list'),
    path('appointments/', views.appointment_list, name='visits'),
    path('appointment/<int:pk>/new-card-record', views.patientcard_create_view, name='new-card-record'),
    path('contact/', views.contact, name='contact'),
    path('services/', views.ServicesListView.as_view(), name='services'),
    path('invoice/', views.invoice_list_view, name='invoices'),
    path('invoice/<int:id>/', views.invoice_detail_view, name='invoice-detail'),
    path('profile/', views.profile, name='profilis'),
    path('profile/update/', views.doctor_profile_edit, name='doctor-update'),
    path('profile/patient-update/', views.patient_profile_edit, name='patient-update'),
    path('search/', views.search, name='search'),
    path(r'^i18n/', include('django.conf.urls.i18n')),
]

Clinic_site-Django/clinic/visits/models.py
import datetime

from PIL import Image
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    is_doctor = models.BooleanField(default=False)
    is_patient = models.BooleanField(default=False)
    name = models.CharField(max_length=100)


class Patient(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, related_name='patient')
    name = models.CharField(_('name'), max_length=50, null=True)
    birth_day = models.DateField(_('birth day'), null=True)
    email = models.CharField(_('email'), max_length=70, null=True)
    phone_number = models.CharField(_('phone number'), max_length=20, null=True)
    address = models.CharField(_('address'), max_length=200, null=True)
    SD = models.CharField(_('Social Insurance ID'), max_length=10, null=True)

    @property
    def balance(self):
        rows = InvoiceLine.objects.filter(invoice_ID__patient_ID=self.user_id).all()
        sum = 0
        for row in rows:
            sum += row.sum
        return sum

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Patient")
        verbose_name_plural = _("Patients")


class PatientCard(models.Model):
    patient_ID = models.ForeignKey('Patient', on_delete=models.SET_NULL, null=True, db_constraint=False)
    doctor_ID = models.ForeignKey('Doctor', on_delete=models.SET_NULL, null=True, db_constraint=False)
    symptoms = models.CharField(_('symptoms'), max_length=5000)
    treatment = models.CharField(_('treatment'), max_length=5000)
    prognosis = models.CharField(_('prognosis'), max_length=1000)
    comments = models.CharField(_('comments'), max_length=5000)
    appointment_ID = models.OneToOneField('Appointment', on_delete=models.CASCADE, related_name='patientcard')
    invoice_ID = models.ForeignKey('Invoice', on_delete=models.SET_NULL, null=True, db_constraint=False)

    class Meta:
        verbose_name = _("Patient Card Record")
        verbose_name_plural = _("Patient Card Records")

    def __str__(self):
        return self.patient_ID.name

    @property
    def status(self):
        if self.appointment_ID.status == 'w':
            return _("Waiting")
        elif self.appointment_ID.status == 'c':
            return _("Completed")
        elif self.appointment_ID.status == 'x':
            return _("Canceled")

    @property
    def visit_date(self):
        date = str(self.appointment_ID.date_time)
        date_time = date[:16]
        return date_time

    @property
    def department(self):
        return self.appointment_ID.department.title


class Doctor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, related_name='doctor')
    name = models.CharField(_('name'), max_length=50, null=True)
    phone_number = models.CharField(_('phone number'), max_length=20)
    email = models.CharField(_('email'), max_length=70, null=True)
    experience = models.IntegerField(_('experience (years)'), null=True)
    department = models.ManyToManyField('Department',
                                        help_text='Choose the department')

    def display_departments(self):
        return ', '.join(dep.title for dep in self.department.all())

    display_departments.short_description = _('Departments')

    class Meta:
        verbose_name = _('Doctor')
        verbose_name_plural = _('Doctors')

    def __str__(self):
        return self.name


class Appointment(models.Model):
    patient_ID = models.ForeignKey('Patient', on_delete=models.SET_NULL, null=True, related_name='appointment', db_constraint=False)
    doctor_ID = models.ForeignKey('Doctor', null=True, on_delete=models.SET_NULL, related_name='appointment', db_constraint=False)
    date_time = models.DateTimeField(_('appointment date and time'))
    department = models.ForeignKey('Department', on_delete=models.SET_NULL, null=True, related_name='appointment')
    STATUS = (
        ('w', (_('waiting'))),
        ('c', (_('completed'))),
        ('x', (_('canceled'))),
    )

    status = models.CharField(max_length=1,
                              choices=STATUS,
                              blank=True,
                              default='w',
                              help_text=(_('Status'))
                              )
    class Meta:
        verbose_name = _("Appointment")
        verbose_name_plural = _("Appointments")

    def __str__(self):
        date = str(self.date_time)
        return f"{self.patient_ID.name}, {date}"

    @property
    def visit_department(self):
        return self.department.title

    @property
    def date_and_time(self):
        date = str(self.date_time)
        datetimes = str(datetime.datetime.strptime(date, "%Y-%m-%d %H:%M:%S"))
        return f"{datetimes}"


class Department(models.Model):
    title = models.CharField(_('Department'), max_length=100)

    def __str__(self):
        return self.title


class Service(models.Model):
    title = models.CharField(_('service'), max_length=100)
    price = models.FloatField(_('price'))
    department_ID = models.ManyToManyField('Department', help_text='Choose the department')

    class Meta:
        verbose_name = _('Service')
        verbose_name_plural = _('Services')

    def __str__(self):
        return f"{self.title}: {self.price} $"


class InvoiceLine(models.Model):
    quantity = models.FloatField(_('Quantity'), default=1)
    price = models.FloatField(_('Price'))
    service_ID = models.ForeignKey('Service', on_delete=models.SET_NULL,
                                   null=True)
    invoice_ID = models.ForeignKey('Invoice', on_delete=models.SET_NULL,
                                   null=True, related_name='invoice_line')
    sum = models.FloatField(verbose_name=_("sum"), null=True, blank=True)

    @property
    def get_sum(self):
        sum = self.quantity * self.price
        return sum

    def save(self, *args, **kwargs):
        self.sum = self.get_sum
        super(InvoiceLine, self).save(*args, **kwargs)

    def __float__(self):
        return self.sum

    def __str__(self):
        return f"{self.service_ID.title}, {self.invoice_ID}"

    class Meta:
        verbose_name = _('Invoice line')
        verbose_name_plural = _('Invoice lines')


def increment_invoice_number():
    last_invoice = Invoice.objects.all().order_by('id').last()
    if not last_invoice:
        return 'CLN1'
    invoice_no = last_invoice.invoice_no
    invoice_int = int(invoice_no.split('CLN')[-1])
    new_invoice_int = invoice_int + 1
    new_invoice_no = 'CLN' + str(new_invoice_int)
    return new_invoice_no


class Invoice(models.Model):
    invoice_no = models.CharField(_('Invoice ID'), max_length=500, default=increment_invoice_number, null=True, blank=True)
    date = models.DateField(_('Invoice date'))
    patient_ID = models.ForeignKey('Patient', on_delete=models.SET_NULL,
                                   null=True)

    STATUS = (
        ('u', (_('unpaid'))),
        ('p', (_('paid'))),
        ('c', (_('canceled'))),
    )

    status = models.CharField(max_length=1,
                              choices=STATUS,
                              blank=True,
                              default='u',
                              help_text=(_('Status')),
                              )

    @property
    def sum(self):
        rows = InvoiceLine.objects.filter(invoice_ID=self.id)
        sum = 0
        for row in rows:
            sum += row.sum
        return sum

    def __str__(self):
        return f"{self.invoice_no} {self.patient_ID.name} {self.date}"

    class Meta:
        verbose_name = _('Invoice')
        verbose_name_plural = _('Invoices')
        ordering = ['date']


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nuotrauka = models.ImageField(_('Image'), default="default.png", upload_to="profile_pics")

    def __str__(self):
        if self.user.is_patient:
            return _("%(username)s profile") % {'username': self.user.patient.name}
        elif self.user.is_doctor:
            return _("%(username)s profile") % {'username': self.user.doctor.name}
        else:
            return _("%(username)s profile") % {'username': self.user.username}

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        super().save(force_insert, force_update, using, update_fields)
        img = Image.open(self.nuotrauka.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.nuotrauka.path)

Clinic_site-Django/clinic/visits/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.db import transaction
from .models import User, Doctor, Patient, Appointment, Department, Profile, PatientCard


class PatientSignUpForm(UserCreationForm):
    name = forms.CharField(required=True)
    birth_day = forms.CharField(required=True)
    email = forms.CharField(required=True)
    phone_number = forms.CharField(required=True)
    address = forms.CharField(required=True)
    SD = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'User', }), label=u'Social Insurance ID',
        max_length=100, required=True)

    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_patient = True
        user.save()
        patient = Patient.objects.create(user=user)
        patient.name = self.cleaned_data.get('name')
        patient.phone_number = self.cleaned_data.get('phone_number')
        patient.address = self.cleaned_data.get('address')
        patient.birth_day = self.cleaned_data.get('birth_day')
        patient.email = self.cleaned_data.get('email')
        patient.SD = self.cleaned_data.get('SD')
        patient.save()
        return user


class DoctorSignUpForm(UserCreationForm):
    name = forms.CharField(required=True)
    phone_number = forms.CharField(required=True)
    email = forms.CharField(required=True)
    experience = forms.CharField(required=True)
    department = forms.CharField(required=True)

    def save(self, commit=True):
        user = super(DoctorSignUpForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_doctor = True
        user.is_staff = True
        user.first_name = self.cleaned_data.get('first_name')
        user.last_name = self.cleaned_data.get('last_name')
        user.save()
        doctor = Doctor.objects.create(user=user)
        doctor.phone_number = self.cleaned_data.get('phone_number')
        doctor.designation = self.cleaned_data.get('designation')
        doctor.save()
        return user


class AppointmentDepartmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ('department',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['department'].queryset = Department.objects.all()


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class DoctorUpdateForm(forms.ModelForm):
    class Meta:
        model = Doctor
        fields = ['name', 'phone_number', 'experience', 'department']


class PatientUpdateForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ['name', 'birth_day', 'phone_number', 'address', 'SD']


class ProfilisUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['nuotrauka']

class PatientCardUpdateForm(forms.ModelForm):
    symptoms = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'PatientCard', }), label=u'Symptoms',
        max_length=1000, required=True)
    treatment = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'PatientCard', }), label=u'Treatment',
        max_length=1000, required=True)
    prognosis = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'PatientCard', }), label=u'Prognosis',
        max_length=1000, required=True)
    comments = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'PatientCard', }), label=u'Comments',
        max_length=1000, required=True)

    class Meta:
        model = PatientCard
        fields = '__all__'

Clinic_site-Django/clinic/visits/templates/InvoiceLine_detailview.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<h1>Invoice ID {{invoice.invoice_no}}</h1>
<div class="visits-list">

    <table class="table table-hover visits-list-table" style="background-color:rgb(102,205,170);opacity:0.8;">

        <tr>
            <th scope="col">{%trans "Date"%}</th>
            <th scope="col">{%trans "Invoice ID"%}</th>
            <th scope="col">{%trans "Sum"%} $</th>
            <th scope="col">{%trans "Status"%}</th>

        </tr>

        <tr>
            <td>{{invoice.date | date:"Y-m-d"}}</td>
            <td>{{invoice.invoice_no}}</td>
            <td>{{invoice.sum}}</td>
            {%if invoice.status == 'u'%}
            <td>{%trans "Unpaid"%}</td>
            {%elif invoice.statu == 'p'%}
            <td>{%trans "Paid"%}</td>
            {%elif invoice.statu == 'c'%}
            <td>{%trans "Canceled"%}</td>

            {%endif%}
        </tr>

    </table>

    <table class="table table-hover visits-list-table" style="background-color:rgb(192,192,192);opacity:0.8;">
        <tr>
            <th scope="col">{%trans "Service"%}</th>
            <th scope="col">{%trans "Sum"%} $</th>
        </tr>
        {%for line in invoice_lines%}
        <tr>
            <td>{{line.service_ID.title}}</td>
            <td>{{line.sum}}</td>
        </tr>
        {%endfor%}
    </table>


</div>
{% endblock %}

Clinic_site-Django/clinic/visits/templates/appointment_create.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<div class="content-section">
    <h2>{%trans "New Appointment"%}</h2>

    <div class="bootstrap-iso" style="background-color:transparent;">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <select id="doctor" name="doctor" class="form-control">
                                <option disabled="true" selected>{%trans "Select Doctor" %}</option>
                                {%for d in doctor%}
                                <option value="{{d.name}}">{{d.name}}</option>
                                {%endfor%}
                            </select>
                        </div>
                        <div class="form-group">
                            {%if user.is_doctor%}
                            <select id="patient" name="patient" class="form-control">
                                <option disabled="true" selected>{%trans "Select Patient"%}</option>
                                {%for p in patient%}
                                <option value="{{p.name}}">{{p.name}}</option>
                                {%endfor%}
                            </select>
                            {%endif%}
                        </div>

                        <div class="form-group ">
                            <div class="input-group">
                                <input type='text' id="picker" class="form-control" name="date" placeholder="{% blocktrans %}Select Date{% endblocktrans %}"/>
                            </div>
                        </div>

                        <div class="form-group">
                            <div>
                                <button class="btn btn-success " name="submit" type="submit">
                                    {%trans "Submit"%}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

Clinic_site-Django/clinic/visits/templates/appointment_listview.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<h1>{%trans "Appointments" %}</h1>

<div class="visits-list">
    <table class="table table-hover" style="background-color:rgb(192,192,192);opacity:0.8;">
        {%if visits%}
        <tr>
            <th scope="col">{%trans "Visit Date"%}</th>
            <th scope="col">{%trans "Department" %}</th>
            <th scope="col">{%trans "Patient"%}</th>
            <th scope="col">{%trans "Status"%}</th>
        </tr>
        {%for visit in visits%}
        <tr>
            <td>{{visit.date_time|date:"Y-m-d H:i"}}</td>
            <td>{{visit.department.title}}</td>
            <td>{{visit.patient_ID.name}}</td>
            {%if visit.status == 'w'%}
            <td><a class="btn btn-secondary btn-sm" href="{% url 'new-card-record' visit.id %}"/>{%trans "Waiting"%}</td>
            {%elif visit.status == 'x'%}
            <td><a class="btn btn-danger btn-sm" href="#"/>{%trans "Calceled"%}</td>
            {%elif visit.status == 'c'%}
            <td><a class="btn btn-success btn-sm" href="{%url 'visit-detail' visit.patientcard.id %}"/>{%trans "Completed"%}</td>
            {%endif%}
            {%endfor%}
    </table>


    <div class="container puslapiai">
        <nav aria-label="...">
            {% if visits.has_other_pages %}
            <ul class="pagination pagination-sm justify-content-end">
                {% for i in visits.paginator.page_range %}
                {% if visits.number == i %}
                <li class="page-item active">
                    <a class="page-link" href="#">{{ i }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
                {% endif %}
                {% endfor %}
            </ul>
            {% endif %}
        </nav>
    </div>
</div>

{% endif %}
{% endblock %}

Clinic_site-Django/clinic/visits/templates/doctor_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block content %}
<div class="visits-list">
    <table class="table table-hover" style="background-color:rgb(102,205,170);opacity:0.8;">
        <tr>
            <th scope="col">{%trans "Name"%}</th>
            <th scope="col">{%trans "Email"%}</th>
            <th scope="col">{%trans "Department"%}</th>
            <th scope="col">{%trans "Phone"%}</th>
            <th scope="col">{%trans "Experience (y)"%}</th>
        </tr>
        <tr>
            <td>{{doctor.name}}</td>
            <td>{{doctor.email}}</td>
            <td>{{doctor.display_departments}}</td>
            <td>{{doctor.phone_number}}</td>
            <td>{{doctor.experience}}</td>
        </tr>
    </table>
</div>

<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-3">{%trans "Update Personal Information"%}</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-success" type="submit">{%trans "Update"%}</button>
        </div>
    </form>
</div>
{% endblock content %}

Clinic_site-Django/clinic/visits/templates/invoices_listview.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<h1>{%trans "My Invoices"%}</h1>
<div class="visits-list">
    {%if invoices%}

    <table class="table table-hover visits-list-table" style="background-color:rgb(192,192,192);opacity:0.8;">

        <tr>
            <th scope="col">{%trans "Date"%}</th>
            <th scope="col">{%trans "Invoice ID"%}</th>
            <th scope="col">{%trans "Sum"%} $</th>
            <th scope="col">{%trans "Invoice Status"%}</th>
            <th scope="col">{%trans "Detail"%}</th>
        </tr>
        {%for invoice in invoices%}
        <tr>
            <td>{{invoice.date | date:"Y-m-d"}}</td>
            <td>{{invoice.invoice_no}}</td>
            <td>{{invoice.sum}}</td>
            {%if invoice.status == 'u'%}
            <td>{%trans "Unpaid"%}</td>
            <td><a class="btn btn-danger btn-sm" href="{%url 'invoice-detail' invoice.id%}"/>{%trans "Detail"%}</td>
            {%elif invoice.status == 'p'%}
            <td>{%trans "Paid"%}</td>
            <td><a class="btn btn-sccess btn-sm" href="{%url 'invoice-detail' invoice.id%}"/>{%trans "Detail"%}</td>
            {%elif invoice.status == 'c'%}
            <td>{%trans "Canceled"%}</td>
            <td><a class="btn btn-secondary btn-sm" href="{%url 'invoice-detail' invoice.id%}"/>{%trans "Detail"%}</td>

            {%endif%}
        </tr>
        {%endfor%}
    </table>
    <div class="container puslapiai">
        <nav aria-label="...">
            {% if invoices.has_other_pages %}
            <ul class="pagination pagination-sm justify-content-end">
                {% for i in invoices.paginator.page_range %}
                {% if invoices.number == i %}
                <li class="page-item active">
                    <a class="page-link">{{ i }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
                {% endif %}
                {% endfor %}
            </ul>
            {% endif %}
        </nav>
    </div>

    {% else %}
    <p>{%trans "There are no invoices."%}</p>

    {% endif %}
</div>
{% endblock %}

Clinic_site-Django/clinic/visits/templates/patientCard_createview_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% load i18n %}

<h2> {{object.appointment_ID.date_time|date:"Y-m-d"}} {%trans "Patient's"%} {{object.patient_ID.name}} {%trans "New Card Record Update"%}</h2>
<form method="POST">
    {% csrf_token %}

    <div class="form-group">
        <label for="symptoms">{%trans "Symptoms"%}</label>
        <textarea class="form-control" id="symptoms" name="symptoms" rows="5"></textarea>
    </div>
    <div class="form-group">
        <label for="treatment">{%trans "Treatment"%}</label>
        <textarea class="form-control" id="treatment" name="treatment" rows="5"></textarea>
    </div>
    <div class="form-group">
        <label for="prognosis">{%trans "Prognosis"%}</label>
        <textarea class="form-control" id="prognosis" name="prognosis" rows="5"></textarea>
    </div>
    <div class="form-group">
        <label for="comments">{%trans "Comments"%}</label>
        <textarea class="form-control" id="comments" name="comments" rows="5"></textarea>
    </div>
    <div class="custom-control custom-radio">
        <input type="radio" id="customRadio2" name="customRadio" class="custom-control-input" value="c" checked>
        <label class="custom-control-label" for="customRadio2">{%trans "Completed"%}</label>
    </div>
    <div class="custom-control custom-radio">
        <input type="radio" id="customRadio3" name="customRadio" class="custom-control-input" value="x">
        <label class="custom-control-label" for="customRadio3">{%trans "Canceled"%}</label>
    </div>

    <button type="submit" class="btn btn-primary">{%trans "Submit"%}</button>
</form>


{% endblock %}

Clinic_site-Django/clinic/visits/templates/patient_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% load i18n %}
<div class="visits-list">
    <table class="table table-hover" style="background-color:rgb(102,205,170);opacity:0.8;">
        <tr>
            <th scope="col">{%trans "Name"%}</th>
            <th scope="col">{%trans "Email"%}</th>
            <th scope="col">{%trans "Birthday"%}</th>
            <th scope="col">{%trans "Phone"%}</th>
            <th scope="col">{%trans "Address"%}</th>
            <th scope="col">SD</th>
        </tr>
        <tr>
            <td>{{patient.name}}</td>
            <td>{{patient.email}}</td>
            <td>{{patient.birth_day|date:"Y-m-d"}}</td>
            <td>{{patient.phone_number}}</td>
            <td>{{patient.address}}</td>
            <td>{{patient.SD}}</td>
        </tr>
    </table>
</div>

<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-3">{%trans "Update Personal Information"%}</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-success" type="submit">{%trans "Update"%}</button>
        </div>
    </form>
</div>
{% endblock content %}

Clinic_site-Django/clinic/visits/templates/patient_listview.html
{% extends "base.html" %}
{% block content %}
{% load i18n %}
<h1>{%trans "Patients"%}</h1>
<p>
<form action="{% url 'search' %}" method="get" class="form-inline my-2 my-md-0">
    <input name="query" class="form-control" type="text" placeholder="{% blocktrans %}Search{% endblocktrans %}">
</form>
</p>

<div class="visits-list">
    <table class="table table-hover" style="background-color:rgb(192,192,192);opacity:0.8;">
        <tr>
            <th scope="col">{%trans "Name"%}</th>
            <th scope="col">{%trans "Email"%}</th>
            <th scope="col">{%trans "Phone"%}</th>
            <th scope="col">{%trans "Balance"%} $</th>
            <th scope="col">{%trans "Patient Card"%}</th>
        </tr>
        {%for patient in patient_list%}
        <tr>
            <td>{{patient.name}}</td>
            <td>{{patient.email}}</td>
            <td>{{patient.phone_number}}</td>
            {% load humanize %}
            <td>{{patient.balance|floatformat:2|intcomma}}</td>
            <td><a class="btn btn-secondary btn-sm" href="{%url 'patient-card' patient.pk %}">{%trans "View" %}</a></td>
            {%endfor%}
    </table>

</div>
<div class="container puslapiai">
    <nav aria-label="...">
        {% if page_obj.has_other_pages %}
        <ul class="pagination pagination-sm justify-content-end">
            {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
            <li class="page-item active">
                <a class="page-link" href="#">{{ i }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>
            {% endif %}
            {% endfor %}
        </ul>
        {% endif %}
    </nav>
</div>
{% endblock %}

Clinic_site-Django/clinic/visits/templates/services_listview.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<h1>{%trans "Services and Prices"%}</h1>
<div class="visits-list">

    <table class="table table-hover" style="background-color:rgb(192,192,192);opacity:0.8;">

        <tr>
            <th scope="col">{%trans "Service"%}</th>
            <th style="text-align: right;" scope="col">{%trans "Price"%} $</th>
        </tr>
        {%for service in service_list%}
        <tr>
            <td>{{service.title}}</td>
            <td style="text-align:right;">{{service.price}}</td>
            {%endfor%}
    </table>

</div>
{% endblock %}